// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/chat_message.dart';
import 'models/conversation.dart';
import 'models/user_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 6522613810587745459),
      name: 'Conversation',
      lastPropertyId: const obx_int.IdUid(9, 2744350790565832998),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 9143344237830216012),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1719927246755851358),
            name: 'uuid',
            type: 9,
            flags: 34848,
            indexId: const obx_int.IdUid(1, 5752628594938995352)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8688538749845315438),
            name: 'recipientId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1701767791547645518),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5821147896132022305),
            name: 'avatar',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 2168572552233496841),
            name: 'lastMessage',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 2510560740664581042),
            name: 'lastMessageAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 4336788523471131531),
            name: 'isGroup',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 2744350790565832998),
            name: 'unreadCount',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 2555789845053409850),
      name: 'ChatMessage',
      lastPropertyId: const obx_int.IdUid(11, 3482922010449322525),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4030245562507902523),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7060938993946404470),
            name: 'uuid',
            type: 9,
            flags: 34848,
            indexId: const obx_int.IdUid(2, 7876129077669028444)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1994706683563609198),
            name: 'conversationId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 508078200180549323),
            name: 'senderId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 2715579899001820873),
            name: 'text',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 6513924971320100503),
            name: 'isMe',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 4300422145804923634),
            name: 'contentType',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 6391290661585227062),
            name: 'avatar',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 5959002444047524385),
            name: 'sentAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 3817957014483886633),
            name: 'status',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 3482922010449322525),
            name: 'clientMessageId',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 975350030681244582),
      name: 'UserEntity',
      lastPropertyId: const obx_int.IdUid(5, 8436743523843462232),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 297028105845437554),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3080299025170816281),
            name: 'userId',
            type: 9,
            flags: 34848,
            indexId: const obx_int.IdUid(4, 1932339092726144149)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3956675151888553508),
            name: 'username',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7095264111837808138),
            name: 'avatarUrl',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8436743523843462232),
            name: 'updatedAt',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(3, 975350030681244582),
      lastIndexId: const obx_int.IdUid(4, 1932339092726144149),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [4078276390187838145],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    Conversation: obx_int.EntityDefinition<Conversation>(
        model: _entities[0],
        toOneRelations: (Conversation object) => [],
        toManyRelations: (Conversation object) => {},
        getId: (Conversation object) => object.id,
        setId: (Conversation object, int id) {
          object.id = id;
        },
        objectToFB: (Conversation object, fb.Builder fbb) {
          final uuidOffset = fbb.writeString(object.uuid);
          final recipientIdOffset = fbb.writeString(object.recipientId);
          final nameOffset = fbb.writeString(object.name);
          final avatarOffset = fbb.writeString(object.avatar);
          final lastMessageOffset = fbb.writeString(object.lastMessage);
          fbb.startTable(10);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uuidOffset);
          fbb.addOffset(2, recipientIdOffset);
          fbb.addOffset(3, nameOffset);
          fbb.addOffset(4, avatarOffset);
          fbb.addOffset(5, lastMessageOffset);
          fbb.addInt64(6, object.lastMessageAt.millisecondsSinceEpoch);
          fbb.addBool(7, object.isGroup);
          fbb.addInt64(8, object.unreadCount);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final uuidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final recipientIdParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, '');
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final avatarParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final lastMessageParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 14, '');
          final lastMessageAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0));
          final isGroupParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 18, false);
          final unreadCountParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0);
          final object = Conversation(
              id: idParam,
              uuid: uuidParam,
              recipientId: recipientIdParam,
              name: nameParam,
              avatar: avatarParam,
              lastMessage: lastMessageParam,
              lastMessageAt: lastMessageAtParam,
              isGroup: isGroupParam,
              unreadCount: unreadCountParam);

          return object;
        }),
    ChatMessage: obx_int.EntityDefinition<ChatMessage>(
        model: _entities[1],
        toOneRelations: (ChatMessage object) => [],
        toManyRelations: (ChatMessage object) => {},
        getId: (ChatMessage object) => object.id,
        setId: (ChatMessage object, int id) {
          object.id = id;
        },
        objectToFB: (ChatMessage object, fb.Builder fbb) {
          final uuidOffset = fbb.writeString(object.uuid);
          final conversationIdOffset = fbb.writeString(object.conversationId);
          final senderIdOffset = fbb.writeString(object.senderId);
          final textOffset = fbb.writeString(object.text);
          final avatarOffset =
              object.avatar == null ? null : fbb.writeString(object.avatar!);
          final clientMessageIdOffset = object.clientMessageId == null
              ? null
              : fbb.writeString(object.clientMessageId!);
          fbb.startTable(12);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uuidOffset);
          fbb.addOffset(2, conversationIdOffset);
          fbb.addOffset(3, senderIdOffset);
          fbb.addOffset(4, textOffset);
          fbb.addBool(5, object.isMe);
          fbb.addInt64(6, object.contentType);
          fbb.addOffset(7, avatarOffset);
          fbb.addInt64(8, object.sentAt.millisecondsSinceEpoch);
          fbb.addInt64(9, object.status);
          fbb.addOffset(10, clientMessageIdOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final uuidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final conversationIdParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, '');
          final senderIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final textParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final contentTypeParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          final isMeParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 14, false);
          final avatarParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 18);
          final sentAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0));
          final statusParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0);
          final clientMessageIdParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 24);
          final object = ChatMessage(
              id: idParam,
              uuid: uuidParam,
              conversationId: conversationIdParam,
              senderId: senderIdParam,
              text: textParam,
              contentType: contentTypeParam,
              isMe: isMeParam,
              avatar: avatarParam,
              sentAt: sentAtParam,
              status: statusParam,
              clientMessageId: clientMessageIdParam);

          return object;
        }),
    UserEntity: obx_int.EntityDefinition<UserEntity>(
        model: _entities[2],
        toOneRelations: (UserEntity object) => [],
        toManyRelations: (UserEntity object) => {},
        getId: (UserEntity object) => object.id,
        setId: (UserEntity object, int id) {
          object.id = id;
        },
        objectToFB: (UserEntity object, fb.Builder fbb) {
          final userIdOffset = fbb.writeString(object.userId);
          final usernameOffset = fbb.writeString(object.username);
          final avatarUrlOffset = fbb.writeString(object.avatarUrl);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, userIdOffset);
          fbb.addOffset(2, usernameOffset);
          fbb.addOffset(3, avatarUrlOffset);
          fbb.addInt64(4, object.updatedAt.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final userIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final usernameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final avatarUrlParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0));
          final object = UserEntity(
              id: idParam,
              userId: userIdParam,
              username: usernameParam,
              avatarUrl: avatarUrlParam,
              updatedAt: updatedAtParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Conversation] entity fields to define ObjectBox queries.
class Conversation_ {
  /// see [Conversation.id]
  static final id =
      obx.QueryIntegerProperty<Conversation>(_entities[0].properties[0]);

  /// see [Conversation.uuid]
  static final uuid =
      obx.QueryStringProperty<Conversation>(_entities[0].properties[1]);

  /// see [Conversation.recipientId]
  static final recipientId =
      obx.QueryStringProperty<Conversation>(_entities[0].properties[2]);

  /// see [Conversation.name]
  static final name =
      obx.QueryStringProperty<Conversation>(_entities[0].properties[3]);

  /// see [Conversation.avatar]
  static final avatar =
      obx.QueryStringProperty<Conversation>(_entities[0].properties[4]);

  /// see [Conversation.lastMessage]
  static final lastMessage =
      obx.QueryStringProperty<Conversation>(_entities[0].properties[5]);

  /// see [Conversation.lastMessageAt]
  static final lastMessageAt =
      obx.QueryDateProperty<Conversation>(_entities[0].properties[6]);

  /// see [Conversation.isGroup]
  static final isGroup =
      obx.QueryBooleanProperty<Conversation>(_entities[0].properties[7]);

  /// see [Conversation.unreadCount]
  static final unreadCount =
      obx.QueryIntegerProperty<Conversation>(_entities[0].properties[8]);
}

/// [ChatMessage] entity fields to define ObjectBox queries.
class ChatMessage_ {
  /// see [ChatMessage.id]
  static final id =
      obx.QueryIntegerProperty<ChatMessage>(_entities[1].properties[0]);

  /// see [ChatMessage.uuid]
  static final uuid =
      obx.QueryStringProperty<ChatMessage>(_entities[1].properties[1]);

  /// see [ChatMessage.conversationId]
  static final conversationId =
      obx.QueryStringProperty<ChatMessage>(_entities[1].properties[2]);

  /// see [ChatMessage.senderId]
  static final senderId =
      obx.QueryStringProperty<ChatMessage>(_entities[1].properties[3]);

  /// see [ChatMessage.text]
  static final text =
      obx.QueryStringProperty<ChatMessage>(_entities[1].properties[4]);

  /// see [ChatMessage.isMe]
  static final isMe =
      obx.QueryBooleanProperty<ChatMessage>(_entities[1].properties[5]);

  /// see [ChatMessage.contentType]
  static final contentType =
      obx.QueryIntegerProperty<ChatMessage>(_entities[1].properties[6]);

  /// see [ChatMessage.avatar]
  static final avatar =
      obx.QueryStringProperty<ChatMessage>(_entities[1].properties[7]);

  /// see [ChatMessage.sentAt]
  static final sentAt =
      obx.QueryDateProperty<ChatMessage>(_entities[1].properties[8]);

  /// see [ChatMessage.status]
  static final status =
      obx.QueryIntegerProperty<ChatMessage>(_entities[1].properties[9]);

  /// see [ChatMessage.clientMessageId]
  static final clientMessageId =
      obx.QueryStringProperty<ChatMessage>(_entities[1].properties[10]);
}

/// [UserEntity] entity fields to define ObjectBox queries.
class UserEntity_ {
  /// see [UserEntity.id]
  static final id =
      obx.QueryIntegerProperty<UserEntity>(_entities[2].properties[0]);

  /// see [UserEntity.userId]
  static final userId =
      obx.QueryStringProperty<UserEntity>(_entities[2].properties[1]);

  /// see [UserEntity.username]
  static final username =
      obx.QueryStringProperty<UserEntity>(_entities[2].properties[2]);

  /// see [UserEntity.avatarUrl]
  static final avatarUrl =
      obx.QueryStringProperty<UserEntity>(_entities[2].properties[3]);

  /// see [UserEntity.updatedAt]
  static final updatedAt =
      obx.QueryDateProperty<UserEntity>(_entities[2].properties[4]);
}
